name: "Node.js CI"

on:
  push:
      branches:
        - master

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - name: Check code meets quality standards
      id: code-inspector
      uses: codeinspectorio/github-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
        min_quality_grade: 'WARNING'
        min_quality_score: '50'
        max_defects_rate: '0.0001'
        max_complex_functions_rate: '0.0001'
        max_long_functions_rate: '0.0001'
        project_name: ''
        max_timeout_sec: '600'
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    name: Codacy Analysis CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli-action@master
  release:
    name: start
    runs-on: windows-latest
    strategy:
        matrix:
            node-version: [12.x, 14.x]
    steps:
        - name: checkout
          uses: actions/checkout@v2.3.4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2.1.3
          with:
              node-version: ${{ matrix.node-version }}
        - run: npm i
        - run: npm start --if-present
