name: "Node.js CI"

on:
  push:
      branches:
        - master

jobs:
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    name: Codacy Analysis CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli-action@master
  release:
    name: start
    runs-on: windows-latest
    strategy:
        matrix:
            node-version: [12.x, 14.x]
    steps:
        - name: checkout
          uses: actions/checkout@v2.3.4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2.1.3
          with:
              node-version: ${{ matrix.node-version }}
        - run: npm i
        - run: npm start --if-present
