name: "publish"

on:
  push:
      branches:
        - master

jobs:
  release:
    name: publish
    runs-on: windows-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2.3.4
        - name: node
          uses: actions/setup-node@v2.1.3
          with:
              node-version: 12
              registry-url: https://www.npmjs.com/package/
        - name: publish
          run: npm publish --access public
          env:
              NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}