name: "publish"

on:
  push:
      branches:
        - master

jobs:
  release:
    name: publish
    runs-on: self-hosted

    strategy:
        matrix:
            node-version: [10.x, 12.x, 14.x]

    steps:
        - name: checkout
          uses: actions/checkout@v2.3.4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2.1.3
          with:
              node-version: ${{ matrix.node-version }}
              registry-url: https://registry.npmjs.org/
        - run: npm i
        - run: npm start --if-present
        - name: publish
          run: npm publish
          env:
              NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}